services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      # accept green or yellow for single-node setups (replica allocation may be delayed)
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -E -q '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  search_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:5000"
