services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      # accept green or yellow for single-node setups (replica allocation may be delayed)
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health | grep -E -q '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  search_api:
    image: python:3.10-slim
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    # fail fast on dependency installation errors (no || true). Use set -e so the container
    # will stop if pip install fails and we can see the root cause in logs.
    command: /bin/sh -c "set -e; python -m pip install --upgrade pip && pip install -r project/elastic_search/requirements.txt && pip install -r project/ganimator/requirements.txt; python3 project/search_api/search_service.py"
